# Required python packages to generate the documentation
# * mkdocs
# * mkdocs-material
# * pygments
# * pymdown-extensions
# * mknotebooks

# Project information
site_name: 'Nanocompore'
site_description: 'Compare nanopore signal to find modifications'
site_author: 'Adrien Leger & Tommaso Leonardi'
site_url: 'http://nanocompore.rna.rocks'

# Repository
repo_name: 'tleonardi/nanocompore'
repo_url: 'https://github.com/tleonardi/nanocompore'

# Copyright
copyright: 'Copyright &copy; 2019 Adrien Leger & Tommaso Leonardi'

# Navigation menu
nav:
    - Home: index.md
    - Installation instructions: installation.md
    - Data preparation: data_preparation.md
    - Usage:
        - Running Nanocompore: usage.md
        - Outputs: output.md
        - Plotting: plotting.md
        - Data API: data_api.md
        - Plotting API: plotting_api.md
        # - Collapse nanopolish data at kmer level: demo/Eventalign_collapse_usage.ipynb
        # - Compare samples with SampComp: demo/SampComp_usage.ipynb
        # - Generate plots and tables with SampCompDB: demo/SampCompDB_usage.ipynb
        # - Generate simulated reads: demo/SimReads_usage.ipynb
    - Alternative and complementary packages: alternative.md
    - Citing: citing.md
    - Contributing: contributing.md
    - Code of conduct: code_of_conduct.md
    - Licence: licence.md
    - Changelog: changelog.md

# Theme customization
theme:
    name: 'material'
    highlightjs: true
    font: false

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: tleonardi
      repo: nanocompore
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - def_list

plugins:
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: numpy
#   - mknotebooks

