# === REQUIRED FIELDS ===

# Specify all the conditions and samples to bo analysed.
# Each sample should have paths to a bam and a pod5 file.
data:
  # Only two conditions are supported
  condition1:
    sample1:
      bam: "/path/to/file.bam"
      pod5: "/path/to/file.pod5"
    sample2:
      bam: "/path/to/file.bam"
      pod5: "/path/to/file.pod5"
    # you can list as many samples as you want
  condition2:
    sample3:
      bam: "/path/to/file.bam"
      pod5: "/path/to/file.pod5"
    sample4:
      bam: "/path/to/file.bam"
      pod5: "/path/to/file.pod5"


# reference genome/transcriptome in fasta format
fasta: "/path/to/reference.fa"


# === OPTIONAL FIELDS ===

# The kit that was used for sequencing.
# kit: "RNA002"

# Number of threads to use.
# Note that 1 thread is used for reading the data and one for writing the output.
# The number of processing threads is hence nthreads-2
# nthreads: 3

# Overwrite existing output files
# overwrite: False

# Path to the output directory
# outpath: "nanocompore_output"

# Text prefix for all the files generated by Nanocompore
# outprefix: "out"

# BED file with annotation of transcriptome used for mapping
# bed: "/path/to/annotation.bed"

# -- Transcript filtering options --

# Minimum coverage to consider a transcript for analysis
# min_coverage: 30

# Transcripts with high coverage will be downsampled to this value
# downsample_high_coverage: 5000

# Minimum length of a reference transcript to include it in the analysis
# min_ref_length: 100

# -- Statistical testing options --

# A list of comparison methods to use.
# Currently supported methods are:
# - GAUSSIAN_MIXTURE_MODEL
# - KOLMOGOROV_SMIRNOV
# - MANN_WHITNEY
# - T_TEST
# You can also use abbreviations:
# - GMM
# - KS
# - MW
# - TT
# comparison_methods:
#   - GAUSSIAN_MIXTURE_MODEL
#   - KOLMOGOROV_SMIRNOV

# Sequence context for combining p-values.
# The value can be in the range [0, 4]
# sequence_context: 0

# Type of weights to use for combining p-values
# sequence_context_weights: 'uniform'

# Adjusted p-value threshold for reporting significant sites
# pvalue_threshold: 0.05

# Use logistic regression testing downstream of GMM method.
# This is the default.
# logit: True

# Use Anova test downstream of GMM method
# anova: False

# If True runtime warnings during the ANOVA tests don't raise an error
# allow_warnings: False

# --- Verbosity options ---

# Set the log level. Possible values are:
# "warning", "info", and "debug"
# log_level: 'info'

# Display a progress bar during execution
# progress: False
